### ISSUE TITLE
Logitech GHub installation fails

### ISSUE THREAD

**Issue by andrewvaughan** [Homebrew/homebrew-cask-drivers#1971]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Attempting to install `logitech-g-hub` fails with the error message:

```
» brew install --force --cask logitech-g-hub
```

```
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/logitech-g-hub/latest/lghub_installer.app/Contents/MacOS/lghub_installer --silent` exited with . Here's the output:

libc++abi.dylib: terminating with uncaught exception of type thekogans::util::Exception: [0x2:2 - No such file or directory]
```

#### Command that failed

```
brew install --cask logitech-g-hub
```

#### Output of command with `--verbose --debug`

```
» brew install --verbose --debug --cask logitech-g-hub
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.zip
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.6.1-25-gfc921bb\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.0.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.zip
Already downloaded: /Users/andrew/Library/Caches/Homebrew/downloads/c1f27082ec37a0f6e36a63aa0ed451c8834249e061f0dc7b82f8e946093c7c3a--lghub_installer.zip
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/andrew/Library/Caches/Homebrew/downloads/c1f27082ec37a0f6e36a63aa0ed451c8834249e061f0dc7b82f8e946093c7c3a--lghub_installer.zip
/usr/bin/xattr -p com.apple.quarantine /Users/andrew/Library/Caches/Homebrew/downloads/c1f27082ec37a0f6e36a63aa0ed451c8834249e061f0dc7b82f8e946093c7c3a--lghub_installer.zip
==> /Users/andrew/Library/Caches/Homebrew/downloads/c1f27082ec37a0f6e36a63aa0ed451c8834249e061f0dc7b82f8e946093c7c3a--lghub_installer.zip is quarantined
Warning: No checksum defined for cask 'logitech-g-hub', skipping verification.
hdiutil imageinfo -format /Users/andrew/Library/Caches/Homebrew/downloads/c1f27082ec37a0f6e36a63aa0ed451c8834249e061f0dc7b82f8e946093c7c3a--lghub_installer.zip
zipinfo -1 /Users/andrew/Library/Caches/Homebrew/downloads/c1f27082ec37a0f6e36a63aa0ed451c8834249e061f0dc7b82f8e946093c7c3a--lghub_installer.zip
==> Installing Cask logitech-g-hub
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/andrew/Library/Caches/Homebrew/downloads/c1f27082ec37a0f6e36a63aa0ed451c8834249e061f0dc7b82f8e946093c7c3a--lghub_installer.zip
zipinfo -1 /Users/andrew/Library/Caches/Homebrew/downloads/c1f27082ec37a0f6e36a63aa0ed451c8834249e061f0dc7b82f8e946093c7c3a--lghub_installer.zip
ditto -x -k /Users/andrew/Library/Caches/Homebrew/downloads/c1f27082ec37a0f6e36a63aa0ed451c8834249e061f0dc7b82f8e946093c7c3a--lghub_installer.zip /var/folders/bx/1hy3vprx3512y62mqz9yzp7m0000gn/T/d20201210-57212-13s3u7u
cp -pR /var/folders/bx/1hy3vprx3512y62mqz9yzp7m0000gn/T/d20201210-57212-13s3u7u/lghub_installer.app/. /usr/local/Caskroom/logitech-g-hub/latest/lghub_installer.app
chmod -Rf +w /var/folders/bx/1hy3vprx3512y62mqz9yzp7m0000gn/T/d20201210-57212-13s3u7u
==> Verifying Gatekeeper status of /Users/andrew/Library/Caches/Homebrew/downloads/c1f27082ec37a0f6e36a63aa0ed451c8834249e061f0dc7b82f8e946093c7c3a--lghub_installer.zip
/usr/bin/xattr -p com.apple.quarantine /Users/andrew/Library/Caches/Homebrew/downloads/c1f27082ec37a0f6e36a63aa0ed451c8834249e061f0dc7b82f8e946093c7c3a--lghub_installer.zip
==> /Users/andrew/Library/Caches/Homebrew/downloads/c1f27082ec37a0f6e36a63aa0ed451c8834249e061f0dc7b82f8e946093c7c3a--lghub_installer.zip is quarantined
==> Propagating quarantine from /Users/andrew/Library/Caches/Homebrew/downloads/c1f27082ec37a0f6e36a63aa0ed451c8834249e061f0dc7b82f8e946093c7c3a--lghub_installer.zip to /usr/local/Caskroom/logitech-g-hub/latest
/usr/bin/xattr -p com.apple.quarantine /Users/andrew/Library/Caches/Homebrew/downloads/c1f27082ec37a0f6e36a63aa0ed451c8834249e061f0dc7b82f8e946093c7c3a--lghub_installer.zip
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5fd284c1\;Homebrew\\x20Cask\;1D69D524-7F2D-45A1-ABA3-8A890F926EF3
==> Creating metadata directory /usr/local/Caskroom/logitech-g-hub/.metadata/latest/20201210203427.129.
==> Creating metadata subdirectory /usr/local/Caskroom/logitech-g-hub/.metadata/latest/20201210203427.129/Casks.
==> Installing artifacts
==> 4 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007feadd17f758 @cask=#<Cask::Cask:0x00007feadd211a90 @token="logitech-g-hub", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/logitech-g-hub.rb>, @tap=#<Tap:0x00007feadd1ea008 @user="Homebrew", @repo="cask-drivers", @name="homebrew/cask-drivers", @full_name="Homebrew/homebrew-cask-drivers", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks>>, @block=#<Proc:0x00007feadd2119f0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/logitech-g-hub.rb:1>, @default_config=#<Cask::Config:0x00007feadd200d80 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/logitech-g-hub>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/logitech-g-hub/.metadata>, @config=#<Cask::Config:0x00007feadc0f9230 @explicit={}>, @dsl=#<Cask::DSL:0x00007feadc0f8f60 @cask=#<Cask::Cask:0x00007feadd211a90 ...>, @token="logitech-g-hub", @version="latest", @sha256=:no_check, @url=#<URL:0x00007feadc0f88d0 @uri=#<URI::HTTPS https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.zip>, @verified="download01.logi.com/", @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:verified=>"download01.logi.com/", :user_agent=>:default}, @caller_location="/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/logitech-g-hub.rb:5:in `block in load'">, @name=["Logitech G HUB"], @homepage="https://www.logitechg.com/en-us/innovation/g-hub.html", @artifacts=#<SortedSet: {...}>, @language_eval=nil>>, @directives={:script=>{:executable=>"/Applications/lghub.app/Contents/Frameworks/lghub_updater.app/Contents/MacOS/lghub_updater", :args=>["--uninstall"], :sudo=>true}, :trash=>"/Users/Shared/LGHUB", :signal=>[]}>, #<Cask::Artifact::Installer:0x00007feadd17ff50 @cask=#<Cask::Cask:0x00007feadd211a90 @token="logitech-g-hub", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/logitech-g-hub.rb>, @tap=#<Tap:0x00007feadd1ea008 @user="Homebrew", @repo="cask-drivers", @name="homebrew/cask-drivers", @full_name="Homebrew/homebrew-cask-drivers", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks>>, @block=#<Proc:0x00007feadd2119f0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/logitech-g-hub.rb:1>, @default_config=#<Cask::Config:0x00007feadd200d80 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/logitech-g-hub>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/logitech-g-hub/.metadata>, @config=#<Cask::Config:0x00007feadc0f9230 @explicit={}>, @dsl=#<Cask::DSL:0x00007feadc0f8f60 @cask=#<Cask::Cask:0x00007feadd211a90 ...>, @token="logitech-g-hub", @version="latest", @sha256=:no_check, @url=#<URL:0x00007feadc0f88d0 @uri=#<URI::HTTPS https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.zip>, @verified="download01.logi.com/", @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:verified=>"download01.logi.com/", :user_agent=>:default}, @caller_location="/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/logitech-g-hub.rb:5:in `block in load'">, @name=["Logitech G HUB"], @homepage="https://www.logitechg.com/en-us/innovation/g-hub.html", @artifacts=#<SortedSet: {...}>, @language_eval=nil>>, @args={:must_succeed=>true, :sudo=>true, :args=>["--silent"], :print_stdout=>true}, @path=#<Pathname:lghub_installer.app/Contents/MacOS/lghub_installer>>, #<Cask::Artifact::PostflightBlock:0x00007feadd17fb68 @cask=#<Cask::Cask:0x00007feadd211a90 @token="logitech-g-hub", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/logitech-g-hub.rb>, @tap=#<Tap:0x00007feadd1ea008 @user="Homebrew", @repo="cask-drivers", @name="homebrew/cask-drivers", @full_name="Homebrew/homebrew-cask-drivers", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks>>, @block=#<Proc:0x00007feadd2119f0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/logitech-g-hub.rb:1>, @default_config=#<Cask::Config:0x00007feadd200d80 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/logitech-g-hub>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/logitech-g-hub/.metadata>, @config=#<Cask::Config:0x00007feadc0f9230 @explicit={}>, @dsl=#<Cask::DSL:0x00007feadc0f8f60 @cask=#<Cask::Cask:0x00007feadd211a90 ...>, @token="logitech-g-hub", @version="latest", @sha256=:no_check, @url=#<URL:0x00007feadc0f88d0 @uri=#<URI::HTTPS https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.zip>, @verified="download01.logi.com/", @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:verified=>"download01.logi.com/", :user_agent=>:default}, @caller_location="/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/logitech-g-hub.rb:5:in `block in load'">, @name=["Logitech G HUB"], @homepage="https://www.logitechg.com/en-us/innovation/g-hub.html", @artifacts=#<SortedSet: {...}>, @language_eval=nil>>, @directives={:postflight=>#<Proc:0x00007feadd17fbb8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/logitech-g-hub.rb:16>}>, #<Cask::Artifact::Zap:0x00007feadd17f190 @cask=#<Cask::Cask:0x00007feadd211a90 @token="logitech-g-hub", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/logitech-g-hub.rb>, @tap=#<Tap:0x00007feadd1ea008 @user="Homebrew", @repo="cask-drivers", @name="homebrew/cask-drivers", @full_name="Homebrew/homebrew-cask-drivers", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks>>, @block=#<Proc:0x00007feadd2119f0@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/logitech-g-hub.rb:1>, @default_config=#<Cask::Config:0x00007feadd200d80 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/logitech-g-hub>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/logitech-g-hub/.metadata>, @config=#<Cask::Config:0x00007feadc0f9230 @explicit={}>, @dsl=#<Cask::DSL:0x00007feadc0f8f60 @cask=#<Cask::Cask:0x00007feadd211a90 ...>, @token="logitech-g-hub", @version="latest", @sha256=:no_check, @url=#<URL:0x00007feadc0f88d0 @uri=#<URI::HTTPS https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.zip>, @verified="download01.logi.com/", @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:verified=>"download01.logi.com/", :user_agent=>:default}, @caller_location="/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/logitech-g-hub.rb:5:in `block in load'">, @name=["Logitech G HUB"], @homepage="https://www.logitechg.com/en-us/innovation/g-hub.html", @artifacts=#<SortedSet: {...}>, @language_eval=nil>>, @directives={:trash=>["~/Library/Application Support/lghub", "~/Library/Caches/com.logi.ghub.installer", "~/Library/Preferences/com.logi.ghub.plist", "~/Library/Saved Application State/com.logi.ghub.savedState"], :signal=>[]}>}>
==> Installing artifact of class Cask::Artifact::Installer
==> Running installer script 'lghub_installer.app/Contents/MacOS/lghub_installer'
/usr/bin/sudo -E -- /usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/logitech-g-hub/latest/lghub_installer.app/Contents/MacOS/lghub_installer --silent
libc++abi.dylib: terminating with uncaught exception of type thekogans::util::Exception: [0x2:2 - No such file or directory]
==> Purging files for version latest of Cask logitech-g-hub
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/logitech-g-hub/latest/lghub_installer.app/Contents/MacOS/lghub_installer --silent` exited with . Here's the output:
libc++abi.dylib: terminating with uncaught exception of type thekogans::util::Exception: [0x2:2 - No such file or directory]

/usr/local/Homebrew/Library/Homebrew/system_command.rb:224:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:63:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:38:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:42:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/installer.rb:38:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:219:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:212:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:107:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:79:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:158:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

#### Output of `brew doctor --verbose`

```
» brew doctor --verbose
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin20
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin20
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20
/usr/local/Homebrew/Library/Homebrew
==> Homebrew Version
2.6.1-25-gfc921bb
==> macOS
11.0.1
==> SIP
Enabled
==> Java
15.0.1
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3752 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (168 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1586 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (166 casks)
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: Your CLT does not support macOS 11.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

#### Output of `brew tap`

```
» brew tap
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
```

**Comment by andrewvaughan** [comment]
Note that I resolved both issues listed (softwareupdate and my path) noticed in `brew doctor` and the issue persists:

```
» brew doctor --verbose                                                          andrew@andrews-mbp
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin20
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin20
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20
/usr/local/Homebrew/Library/Homebrew
==> Homebrew Version
2.6.1-25-gfc921bb
==> macOS
11.0.1
==> SIP
Enabled
==> Java
15.0.1
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3752 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (168 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1586 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (166 casks)
Your system is ready to brew.
```

**Comment by miccal** [comment]
I cannot rerpodice this, although IU do note that the installer downloads some things:
```
|-> brew install logitech-g-hub
==> Downloading https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.zip
######################################################################## 100.0%
Warning: No checksum defined for cask 'logitech-g-hub', skipping verification.
==> Installing Cask logitech-g-hub
Warning: macOS's Gatekeeper has been disabled for this Cask
==> Running installer script 'lghub_installer.app/Contents/MacOS/lghub_installer'
Password:
2020-12-11 09:42:59.804 lghub_installer[72483:4974678] Silently installing...
2020-12-11 09:42:59.804 lghub_installer[72483:4974678] Checking pipeline for updates...
2020-12-11 09:43:01.773 lghub_installer[72483:4975073] Update available!
2020-12-11 09:43:01.773 lghub_installer[72483:4975073] Starting the download...
2020-12-11 09:43:01.887 lghub_installer[72483:4975073] Downloaded 0.000000
2020-12-11 09:43:01.887 lghub_installer[72483:4975073] Rate 0.000000
2020-12-11 09:43:03.722 lghub_installer[72483:4975075] Downloaded 0.932621
2020-12-11 09:43:03.722 lghub_installer[72483:4975075] Rate 11.574074
[SNIP]
2020-12-11 09:43:31.092 lghub_installer[72483:4975073] Downloaded 99.743553
2020-12-11 09:43:31.092 lghub_installer[72483:4975073] Rate 0.000000
2020-12-11 09:43:39.150 lghub_installer[72483:4975062] Update installing!
2020-12-11 09:43:39.154 lghub_installer[72483:4975062] Running sudo command: '/Users/Shared/LGHUB/depots/71012/core/lghub.app/Contents/Frameworks/lghub_updater.app/Contents/MacOS/lghub_updater' --install
2020-12-11 09:43:42.465 lghub_installer[72483:4975062] Shutting down...
GVA info: Successfully connected to the Intel plugin, offline Gen95 
==> Changing ownership of paths required by logitech-g-hub; your password may be necessary
🍺  logitech-g-hub was successfully installed!
```
Perhaps check you internet and/or firewall settings and try again?

**Comment by andrewvaughan** [comment]
I have no other issues with any other installation - I've attempted this with all firewalls disabled, in the DMZ, and had no issues.  Is there a way I can have the files persist from homebrew so I can try running the installer script without the `--silent` attribute?

**Comment by miccal** [comment]
Does `brew install --no-quarantine logitech-g-hub` work?

**Comment by andrewvaughan** [comment]
Sorry, no, same error.

**Comment by andrewvaughan** [comment]
> Does `brew install --no-quarantine logitech-g-hub` work?

Sorry for the double response - just noticed the bot didn't remove the `awaiting user reply` label...

**Comment by vitorgalvao** [comment]
Have you tried installing manually, not through Homebrew Cask?

**Comment by miccal** [comment]
Closing due to lack of reply.
