### ISSUE TITLE
rode-central version mis-match

### ISSUE THREAD

**Issue by endlesslycurious** [Homebrew/homebrew-cask-drivers#2747]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Seems like rode-central is now on version 1.3.8 not 1.3.6 for [Casks/rode-central.rb](https://github.com/Homebrew/homebrew-cask-drivers/blob/HEAD/Casks/rode-central.rb):
```
daniel@macbook ~$ brew install rode-central
==> Downloading https://cdn1.rode.com/rodecentral_installation_file_mac.zip
Already downloaded: /Users/daniel/Library/Caches/Homebrew/downloads/da20c72b34f27239f883f3ded9e79043434a4f5aa6665d8ef5c0550e2cecbf53--rodecentral_installation_file_mac.zip
Warning: No checksum defined for cask 'rode-central', skipping verification.
==> Installing Cask rode-central
==> Running installer for rode-central; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
==> Purging files for version 1.3.6 of Cask rode-central
Error: Could not find PKG source file 'RODE Central macOS v1.3.6/RODE Central Installer.pkg', found 'RODE Central v1.3.8_macOS/RODE Central Installer.pkg' instead.
```

### Command that failed

brew install rode-central

### Output of command with `--verbose --debug`

```shell
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://cdn1.rode.com/rodecentral_installation_file_mac.zip
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.4.5-16-gf6ab300\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.3.1\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://cdn1.rode.com/rodecentral_installation_file_mac.zip
Already downloaded: /Users/daniel/Library/Caches/Homebrew/downloads/da20c72b34f27239f883f3ded9e79043434a4f5aa6665d8ef5c0550e2cecbf53--rodecentral_installation_file_mac.zip
==> Checking quarantine support
/usr/bin/xattr -h
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/daniel/Library/Caches/Homebrew/downloads/da20c72b34f27239f883f3ded9e79043434a4f5aa6665d8ef5c0550e2cecbf53--rodecentral_installation_file_mac.zip
/usr/bin/xattr -p com.apple.quarantine /Users/daniel/Library/Caches/Homebrew/downloads/da20c72b34f27239f883f3ded9e79043434a4f5aa6665d8ef5c0550e2cecbf53--rodecentral_installation_file_mac.zip
==> /Users/daniel/Library/Caches/Homebrew/downloads/da20c72b34f27239f883f3ded9e79043434a4f5aa6665d8ef5c0550e2cecbf53--rodecentral_installation_file_mac.zip is quarantined
Warning: No checksum defined for cask 'rode-central', skipping verification.
hdiutil imageinfo -format /Users/daniel/Library/Caches/Homebrew/downloads/da20c72b34f27239f883f3ded9e79043434a4f5aa6665d8ef5c0550e2cecbf53--rodecentral_installation_file_mac.zip
zipinfo -1 /Users/daniel/Library/Caches/Homebrew/downloads/da20c72b34f27239f883f3ded9e79043434a4f5aa6665d8ef5c0550e2cecbf53--rodecentral_installation_file_mac.zip
==> Installing Cask rode-central
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/daniel/Library/Caches/Homebrew/downloads/da20c72b34f27239f883f3ded9e79043434a4f5aa6665d8ef5c0550e2cecbf53--rodecentral_installation_file_mac.zip
zipinfo -1 /Users/daniel/Library/Caches/Homebrew/downloads/da20c72b34f27239f883f3ded9e79043434a4f5aa6665d8ef5c0550e2cecbf53--rodecentral_installation_file_mac.zip
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/unzip.rb
/usr/bin/env PATH=/usr/local/opt/unzip/bin:/usr/local/Homebrew/Library/Homebrew/shims/shared:/usr/bin:/bin:/usr/sbin:/sbin unzip -o /Users/daniel/Library/Caches/Homebrew/downloads/da20c72b34f27239f883f3ded9e79043434a4f5aa6665d8ef5c0550e2cecbf53--rodecentral_installation_file_mac.zip -d /private/tmp/d20220405-59466-qcnc37
cp -pR /private/tmp/d20220405-59466-qcnc37/RODE\ Central\ v1.3.8_macOS/. /usr/local/Caskroom/rode-central/1.3.6/RODE\ Central\ v1.3.8_macOS
chmod -Rf +w /private/tmp/d20220405-59466-qcnc37
==> Verifying Gatekeeper status of /Users/daniel/Library/Caches/Homebrew/downloads/da20c72b34f27239f883f3ded9e79043434a4f5aa6665d8ef5c0550e2cecbf53--rodecentral_installation_file_mac.zip
/usr/bin/xattr -p com.apple.quarantine /Users/daniel/Library/Caches/Homebrew/downloads/da20c72b34f27239f883f3ded9e79043434a4f5aa6665d8ef5c0550e2cecbf53--rodecentral_installation_file_mac.zip
==> /Users/daniel/Library/Caches/Homebrew/downloads/da20c72b34f27239f883f3ded9e79043434a4f5aa6665d8ef5c0550e2cecbf53--rodecentral_installation_file_mac.zip is quarantined
==> Propagating quarantine from /Users/daniel/Library/Caches/Homebrew/downloads/da20c72b34f27239f883f3ded9e79043434a4f5aa6665d8ef5c0550e2cecbf53--rodecentral_installation_file_mac.zip to /usr/local/Caskroom/rode-central/1.3.6
/usr/bin/xattr -p com.apple.quarantine /Users/daniel/Library/Caches/Homebrew/downloads/da20c72b34f27239f883f3ded9e79043434a4f5aa6665d8ef5c0550e2cecbf53--rodecentral_installation_file_mac.zip
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;624cbc42\;Homebrew\\x20Cask\;44FA421F-FB78-4309-BF7A-77F9F197F681
==> Creating metadata directory: /usr/local/Caskroom/rode-central/.metadata/1.3.6/20220405221121.862
==> Creating metadata subdirectory: /usr/local/Caskroom/rode-central/.metadata/1.3.6/20220405221121.862/Casks
==> Installing artifacts
==> 2 artifacts defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007fad8b1e2360 @cask=#<Cask::Cask:0x00007fad8f0c9a88 @token="rode-central", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/rode-central.rb>, @source="cask \"rode-central\" do\n  version \"1.3.6\"\n  sha256 :no_check\n\n  url \"https://cdn1.rode.com/rodecentral_installation_file_mac.zip\"\n  name \"Rode Central\"\n  desc \"Configure RØDE device settings, features, functions, and firmware\"\n  homepage \"https://rode.com/software/rode-central\"\n\n  livecheck do\n    url :url\n    strategy :extract_plist\n  end\n\n  depends_on macos: \">= :high_sierra\"\n\n  pkg \"RODE Central macOS v\#{version}/RODE Central Installer.pkg\"\n\n  uninstall pkgutil: \"com.rodecentral.installer\"\nend\n", @tap=#<Tap:0x00007fad8f069228 @user="Homebrew", @repo="cask-drivers", @name="homebrew/cask-drivers", @full_name="Homebrew/homebrew-cask-drivers", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks>>, @block=#<Proc:0x00007fad8f0c98a8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/rode-central.rb:1>, @default_config=#<Cask::Config:0x00007fad8f0b1ca8 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/rode-central>, @metadata_main_container_path=#<Pathname:/usr/local/Caskroom/rode-central/.metadata>, @config=#<Cask::Config:0x00007fad8b1d1358 @explicit={}>, @dsl=#<Cask::DSL:0x00007fad8b1d0070 @cask=#<Cask::Cask:0x00007fad8f0c9a88 ...>, @token="rode-central", @version="1.3.6", @sha256=:no_check, @url=#<URL::DSL:0x00007fad8b1dab88 @uri=#<URI::HTTPS https://cdn1.rode.com/rodecentral_installation_file_mac.zip>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:user_agent=>:default}>, @name=["Rode Central"], @desc="Configure RØDE device settings, features, functions, and firmware", @homepage="https://rode.com/software/rode-central", @livecheck=#<Livecheck:0x00007fad8b1d9ff8 @formula_or_cask=#<Cask::DSL:0x00007fad8b1d0070 ...>, @referenced_cask_name=nil, @referenced_formula_name=nil, @regex=nil, @skip=false, @skip_msg=nil, @strategy=:extract_plist, @url=:url>, @livecheckable=true, @depends_on={:macos=>#<MacOSRequirement: version>="10.13" []>}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/rode-central/1.3.6>, @language_eval=nil>>, @directives={:pkgutil=>"com.rodecentral.installer", :signal=>[]}>, #<Cask::Artifact::Pkg:0x00007fad8b1d8748 @cask=#<Cask::Cask:0x00007fad8f0c9a88 @token="rode-central", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/rode-central.rb>, @source="cask \"rode-central\" do\n  version \"1.3.6\"\n  sha256 :no_check\n\n  url \"https://cdn1.rode.com/rodecentral_installation_file_mac.zip\"\n  name \"Rode Central\"\n  desc \"Configure RØDE device settings, features, functions, and firmware\"\n  homepage \"https://rode.com/software/rode-central\"\n\n  livecheck do\n    url :url\n    strategy :extract_plist\n  end\n\n  depends_on macos: \">= :high_sierra\"\n\n  pkg \"RODE Central macOS v\#{version}/RODE Central Installer.pkg\"\n\n  uninstall pkgutil: \"com.rodecentral.installer\"\nend\n", @tap=#<Tap:0x00007fad8f069228 @user="Homebrew", @repo="cask-drivers", @name="homebrew/cask-drivers", @full_name="Homebrew/homebrew-cask-drivers", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks>>, @block=#<Proc:0x00007fad8f0c98a8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/rode-central.rb:1>, @default_config=#<Cask::Config:0x00007fad8f0b1ca8 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/rode-central>, @metadata_main_container_path=#<Pathname:/usr/local/Caskroom/rode-central/.metadata>, @config=#<Cask::Config:0x00007fad8b1d1358 @explicit={}>, @dsl=#<Cask::DSL:0x00007fad8b1d0070 @cask=#<Cask::Cask:0x00007fad8f0c9a88 ...>, @token="rode-central", @version="1.3.6", @sha256=:no_check, @url=#<URL::DSL:0x00007fad8b1dab88 @uri=#<URI::HTTPS https://cdn1.rode.com/rodecentral_installation_file_mac.zip>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:user_agent=>:default}>, @name=["Rode Central"], @desc="Configure RØDE device settings, features, functions, and firmware", @homepage="https://rode.com/software/rode-central", @livecheck=#<Livecheck:0x00007fad8b1d9ff8 @formula_or_cask=#<Cask::DSL:0x00007fad8b1d0070 ...>, @referenced_cask_name=nil, @referenced_formula_name=nil, @regex=nil, @skip=false, @skip_msg=nil, @strategy=:extract_plist, @url=:url>, @livecheckable=true, @depends_on={:macos=>#<MacOSRequirement: version>="10.13" []>}, @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/rode-central/1.3.6>, @language_eval=nil>>, @path=#<Pathname:/usr/local/Caskroom/rode-central/1.3.6/RODE Central macOS v1.3.6/RODE Central Installer.pkg>, @stanza_options={}>}>
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for rode-central; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
==> Purging files for version 1.3.6 of Cask rode-central
Error: Could not find PKG source file 'RODE Central macOS v1.3.6/RODE Central Installer.pkg', found 'RODE Central v1.3.8_macOS/RODE Central Installer.pkg' instead.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:36:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:240:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:233:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:116:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:71:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:70:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:70:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:179:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### Output of `brew doctor --verbose`

```shell
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/warning-1.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tapioca-0.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/yard-sorbet-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/yard-0.9.27/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/spoom-1.1.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-0.5.9837/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-static-0.5.9837-universal-darwin-14/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-cobertura-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.21.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.12.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.6.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.14.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.13.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-1.26.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-ast-1.16.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec_junit_formatter-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-sorbet-1.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-github-2.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.11.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/rdiscount-2.2.0.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rbi-0.0.14/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unparser-0.6.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/pry-0.14.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parlour-6.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-0.5.9837/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-3.1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-3.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.22.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/method_source-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.8.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrick-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubyntlm-0.6.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.13.3-x86_64-darwin/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/racc-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/racc-1.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-4.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2022.0105/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json_schemer-0.2.20/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/uri_template-0.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hana-1.3.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ecma-re-validator-0.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/regexp_parser-2.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/unf_ext-0.0.8.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/did_you_mean-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/commander-4.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/highline-2.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coderay-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/byebug-11.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/byebug-11.1.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bootsnap-1.11.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/bootsnap-1.11.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/msgpack-1.4.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/msgpack-1.4.5
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.10/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/addressable-2.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/public_suffix-4.0.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.5.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.15.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin21
/Library/Ruby/Site/2.6.0/universal-darwin21
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin21
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin21
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin21
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21
/usr/local/Homebrew/Library/Homebrew
==> Homebrew Version
3.4.5-16-gf6ab300
==> macOS
12.3.1
==> SIP
Enabled
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3990 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (208 casks)
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.3.


Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.3.


Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python3.7m/greenlet/greenlet.h
  /usr/local/include/python3.9/greenlet/greenlet.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  six

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> /Users/daniel/.bash_profile
```

### Output of `brew tap`

```shell
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/core
hudochenkov/sshpass
mongodb/brew
```

**Comment by bevanjkay** [comment]
#2748
